version: 2
jobs:
  build:
    working_directory: ~/grow
    docker:
      - image: grow/grow-internal-image
    steps:
      - checkout

      - run:
          name: Versions
          command: |
            node --version
            gcloud --version
            python --version

      - run:
          name: Virtual Env
          command: virtualenv env --distribute

      - restore_cache:
          key: pip-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: Pip Install
          command: |
            . env/bin/activate
            pip install -r requirements-dev.txt
            pip install coveralls

      - save_cache:
          key: pip-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "env"

      - run:
          name: Run Tests
          command: make test-circle

      - run:
          name: Coveralls
          command: coveralls
