version: 2

shortcuts:
  cache_key: &cache_key pip-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ checksum "Pipfile.lock" }}
  pip_install: &pip_install
    name: Pipenv Install
    command: |
      pipenv install --dev
      . $(pipenv --venv)/bin/activate

jobs:
  pylint:
    working_directory: ~/grow
    docker:
      - image: grow/grow-internal-image:two
    steps:
      - checkout

      - restore_cache:
          key: *cache_key

      - run: *pip_install

      - save_cache:
          key: *cache_key
          paths:
          - /root/.local/share/virtualenvs/

      - run:
          name: Pylint
          command: make test-pylint

  test:
    working_directory: ~/grow
    docker:
      - image: grow/grow-internal-image:two
    steps:
      - checkout

      - restore_cache:
          key: *cache_key

      - run: *pip_install

      - save_cache:
          key: *cache_key
          paths:
          - /root/.local/share/virtualenvs/

      - run:
          name: Run Tests
          command: make test coverage=true

      - run:
          name: Code Coverage
          command: $(pipenv --venv)/bin/codecov

workflows:
  version: 2
  build:
    jobs:
    - pylint
    - test
