version: 2
jobs:
  build:
    working_directory: ~/grow
    docker:
      - image: circleci/python:latest
      - image: circleci/node:latest
      - image: google/cloud-sdk
    steps:
      - checkout

      - run:
          name: Versions
          command: |
            node --version
            gcloud --version
            python --version

      - run:
          name: Virtual Env
          command: virtualenv env --distribute

      - restore_cache:
          key: pip-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: Pip Install
          command: |
            . env/bin/activate
            pip install -r requirements-dev.txt
            pip install coveralls

      - save_cache:
          key: pip-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "env"

      - run:
          name: Run Tests
          command: make test-ci

      - run:
          name: Coveralls
          command: coveralls

      - run:
          name: Install App Engine
          command: gcloud components install app-engine-python
