version: 2

pip_install: &pip_install
  name: Pipenv Install
  command: |
    pipenv install --dev
    . $(pipenv --venv)/bin/activate

jobs:
  pylint:
    working_directory: ~/grow
    docker:
      - image: grow/grow-internal-image:two
    steps:
      - checkout

      - restore_cache:
          key: pip-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ checksum "Pipfile.lock" }}

      - run:
          <<: *pip_install

      - save_cache:
          key: pip-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ checksum "Pipfile.lock" }}
          paths:
          - /root/.local/share/virtualenvs/

      - run:
          name: Pylint
          command: pylint --errors-only .

filter_all_tags: &filter_all_tags
  filters:
    tags:
      only: /.*/

filter_only_tags: &filter_only_tags
  filters:
    tags:
      only: /.*/
    branches:
      ignore: /.*/

workflows:
  version: 2
  build:
    jobs:
    - pylint:
        <<: *filter_all_tags
